/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projettest;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.scene.layout.Pane;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Formation
 */
public class Calculatrice extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Calculatrice
     */
    JButton btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnPlus, btnMoins, btnMult, btnDiv, btnC, btnPoint,egal;
    JTextField resultat;
    Double nombre1,nombre2;
    String chaine,operateur;

    public Calculatrice() {
        initComponents();
        nombre1 =0.0;
        nombre2 = 0.0;
        chaine = "";
        btn0 = new JButton("0");
        btn1 = new JButton("1");
        btn2 = new JButton("2");
        btn3 = new JButton("3");
        btn4 = new JButton("4");
        btn5 = new JButton("5");
        btn6 = new JButton("6");
        btn7 = new JButton("7");
        btn8 = new JButton("8");
        btn9 = new JButton("9");
        btnPlus = new JButton("+");
        btnMoins = new JButton("-");
        btnMult = new JButton("*");
        btnDiv = new JButton("/");
        btnC = new JButton("C");
        btnPoint = new JButton(".");

        JPanel panelBtn = new JPanel(new GridLayout(4, 4));
        panelBtn.add(btn1);
        panelBtn.add(btn2);
        panelBtn.add(btn3);
        panelBtn.add(btnPlus);
        panelBtn.add(btn4);
        panelBtn.add(btn5);
        panelBtn.add(btn6);
        panelBtn.add(btnMoins);
        panelBtn.add(btn7);
        panelBtn.add(btn8);
        panelBtn.add(btn9);
        panelBtn.add(btnMult);
        panelBtn.add(btn0);
        panelBtn.add(btnC);
        panelBtn.add(btnPoint);
        panelBtn.add(btnDiv);

        btn0.addActionListener(this);btn1.addActionListener(this);btn2.addActionListener(this);
        btn3.addActionListener(this);btn4.addActionListener(this);btn5.addActionListener(this);
        btn6.addActionListener(this);btn7.addActionListener(this);btn8.addActionListener(this);
        btn9.addActionListener(this);btnPlus.addActionListener(this);btnMoins.addActionListener(this);
        btnMult.addActionListener(this);btnDiv.addActionListener(this);btnC.addActionListener(this);
        btnPoint.addActionListener(this);
        
        JPanel panelResultat = new JPanel();
        this.resultat = new JTextField("0");
        resultat.setPreferredSize(new Dimension(270, 50));
        panelResultat.setLayout(new FlowLayout());
        panelResultat.add(resultat);

        JPanel panelEgal = new JPanel();
        panelEgal.setLayout(new FlowLayout());
        egal = new JButton(" = ");
        egal.setPreferredSize(new Dimension(270, 50));
        panelEgal.add(egal);
        
        egal.addActionListener(this);

        JPanel pane = new JPanel(new BorderLayout());
        pane.add(panelResultat, BorderLayout.NORTH);
        pane.add(panelBtn, BorderLayout.CENTER);
        pane.add(panelEgal, BorderLayout.SOUTH);

        this.setContentPane(pane);
        this.setSize(300, 300);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculatrice().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
        if (e.getSource().equals(btn0)) {
           // this.nombre1 = nombre1 + Integer.parseInt("0");
            //resultat.setText(""+nombre1);
            chaine = chaine +"0";
            this.resultat.setText(chaine);
            System.out.println("Btn0");
        }
        if (e.getSource().equals(btn1)) {
            chaine = chaine +"1";
            this.resultat.setText(chaine);
            //this.resultat.setText(this.resultat + "0");
            System.out.println("Btn1");
        }
        if (e.getSource().equals(btn2)) {
            chaine = chaine +"2";
            this.resultat.setText(chaine);
            System.out.println("Btn2");
        }
        if (e.getSource().equals(btn3)) {
            chaine = chaine +"3";
            this.resultat.setText(chaine);
            System.out.println("Btn3");
        }
        if (e.getSource().equals(btn4)) {
             chaine = chaine +"4";
            this.resultat.setText(chaine);           
            System.out.println("Btn4");
        }
        if (e.getSource().equals(btn5)) {
            chaine = chaine +"5";
            this.resultat.setText(chaine); 
            System.out.println("Btn5");
        }
        if(e.getSource().equals(btn6)){
            chaine = chaine +"6";
            this.resultat.setText(chaine);
            System.out.println("Btn0");
        }
        if(e.getSource().equals(btn7)){
            chaine = chaine +"7";
            this.resultat.setText(chaine);
            System.out.println("Btn7");
        }
        
        if(e.getSource().equals(btn8)){
            chaine = chaine +"8";
            this.resultat.setText(chaine);  
            System.out.println("Btn8");
        }
        if(e.getSource().equals(btn9)){
            chaine = chaine +"9";
            this.resultat.setText(chaine);
            System.out.println("Btn9");
        }
        if(e.getSource().equals(btnPlus)){
            nombre1 = Double.parseDouble(chaine);
            chaine = "";
            operateur="+";
            this.resultat.setText("0");          
            System.out.println("+");
        }
        if(e.getSource().equals(btnMoins)){
            nombre1 = Double.parseDouble(chaine);
            chaine = "";
            operateur="-";
            this.resultat.setText("0");          
            System.out.println("+");
        }
        if(e.getSource().equals(btnMult)){
            nombre1 = Double.parseDouble(chaine);
            chaine = "";
            operateur="*";
            this.resultat.setText("0");          
            System.out.println("*");
        }
        if(e.getSource().equals(btnDiv)){
            chaine = "";
            operateur="/";
            this.resultat.setText("0");            
            System.out.println("/");
        }        
        if(e.getSource().equals(btnC)){
            nombre1=0.0;
            nombre2=0.0;
            chaine = "";
            operateur=" ";
            this.resultat.setText("0");                     
            System.out.println("Clear");
        }
        if(e.getSource().equals(btnPoint)){
            System.out.println(".");
        }
        if(e.getSource().equals(egal)){
            switch(operateur){
                case "+":
                    nombre2= nombre1 + Double.parseDouble(chaine);
                    this.resultat.setText(""+nombre2);
                    break;
                case "*":
                    nombre2= nombre1 * Double.parseDouble(chaine);
                    this.resultat.setText(""+nombre2);
                    break;
                case "/":
                    nombre2= nombre1 / Double.parseDouble(chaine);
                    this.resultat.setText(""+nombre2);
                    break;
                case "-":
                    nombre2= nombre1 - Double.parseDouble(chaine);
                    this.resultat.setText(""+nombre2);
                    break;
                default:
            }
            //System.out.println(".");
        }
        /// throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
