/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Formation
 */
public class Puissance4Vue extends javax.swing.JFrame {

    /**
     * Creates new form Puissance4Vue
     */
    public Puissance4Vue() {
        initComponents();
        JPanel panelBtn = new JPanel(new GridLayout(6,7));
        
        for(int i=0;i<42;i++){
            JButton btn = new JButton(new ImageIcon("C:\\Users\\Formation\\Documents\\NetBeansProjects\\ProjetTest\\src\\vue\\jeton_blanc.png")); 
            //btn.setEnabled(false);
            panelBtn.add(btn); 
        }
        panelBtn.setBackground(Color.BLUE);
        for (int k = 0; k < 6; k++) {
            for (int j = 0; j < 7; j++) {
                int position = k * 7 + j;
                if (position == 35) {
                    JButton btn = (JButton) panelBtn.getComponent(position);
                    btn.setIcon(new ImageIcon("C:\\Users\\Formation\\Documents\\NetBeansProjects\\ProjetTest\\src\\vue\\jeton_jaune.png"));
                    /*setBackground(
                    new java.awt.Color(0,255,200));*/
                }
                if (position == 39) {
                    JButton btn = (JButton) panelBtn.getComponent(position);
                    btn.setIcon(new ImageIcon("C:\\Users\\Formation\\Documents\\NetBeansProjects\\ProjetTest\\src\\vue\\jeton_rouge.png"));
                    /*setBackground(
                    new java.awt.Color(0,255,200));*/
                }
            }
        }
        this.setSize(370,350);
       this.setContentPane(panelBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puissance4Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puissance4Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puissance4Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puissance4Vue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {             
                new Puissance4Vue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
